### ISSUE TITLE
Matter overdrive crashes with Galacticraft aluminum wires.

### ISSUE THREAD

**Issue by gonenoculer5** [MatterOverdrive/MatterOverdrive-Legacy-Edition#158]
#### Issue Description:
Connecting a galacticraft aluminum wire to a MO charging station (android charger) causes a crash.

#### What happens:
Crash to menu (vanilla fix is installed)

#### What you expected to happen:
Wire to connect and function as intended.

#### How to reproduce:
I am unable to reproduce the error in SP.

#### Affected Versions (Do *not* use "*latest*"):

- MatterOverdrive: MatterOverdrive-1.12.2-0.6.0.176-universal
- Forge: 1.12.2-forge1.12.2-14.23.4.2729
- Minecraft: 1.12.2

#### Crash report, if relevent
https://paste.dimdev.org/desobejeho.mccrash

**Comment by gonenoculer5** [comment]
https://github.com/micdoodle8/Galacticraft/issues/3475

**Comment by gonenoculer5** [comment]
Correction, I was able to reproduce it, but it took quite a while before it happened.

**Comment by radfast** [comment]
hi @gonenoculer5 I'm one of the Galacticraft devs.

I think this issue is on MO's side, but happy to help you where we can.

[Our code](https://github.com/micdoodle8/Galacticraft/blob/MC1.12/src/main/java/micdoodle8/mods/galacticraft/core/energy/EnergyUtil.java#884) is simply calling the `.hasCapability()` function on a `TileEntity`.  I don't even think the `side` is null there, as our [calling code](https://github.com/micdoodle8/Galacticraft/blob/MC1.12/src/main/java/micdoodle8/mods/galacticraft/core/energy/EnergyUtil.java#258) will be calling this from the side the Aluminum Wire is on.
