### ISSUE TITLE
Crash with Buildcraft

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [MatterOverdrive/MatterOverdrive-Legacy-Edition#182]
#### Issue Description:
Crashes when BC is installed

#### What happens:
It doesnt load

#### What you expected to happen:
it loads

#### How to reproduce:
load the game

#### Affected Versions (Do *not* use "*latest*"):

- MatterOverdrive: 0.6.0.197
- Buildcraft: 7.99.18
- Forge: .2759
- Minecraft: 1.12.2

#### Crash report, if relevent
https://paste.dimdev.org/ituxipinin.mccrash

**Comment by CrankySupertoonArchive** [comment]
https://github.com/BuildCraft/BuildCraft/issues/4261

**Comment by adrwa** [comment]
VanillaFix is unsupported please test without vanilla fix

**Comment by AlexIIL** [comment]
This is likely to happen because BuildCraft passes a null player into Item.getTooltip during resource reload (which can happen without a world, and thus without a valid player instance).

I'm not sure what I can do to BuildCraft aside from moving the guide reload code to when the player joins a world (and only reload when there's a valid player in resource reload). but that seems a little hacky. However `Item.getTooltip` is defined as `@Nullable EntityPlayer playerIn` so would it be possible for you to add null checks to MatterOverdrive?

I doubt VanillaFix would cause this particular bug, although you're welcome to try and reproduce this without it.

**Comment by adrwa** [comment]
Item.getTooltip doesnt exist, if you meant Item.addInformation, that does not have an EntityPlayer argument, MO uses Minecraft#player which should not be null when addInformation is ran, i think the better solution would be for BC not to get tooltips of items it shouldn't be touching.

And as for VanillaFix sure it might not cause this issue specifically but i dont have the time to chase issues which use super hacky mods, so i prefer to know that any issue with vanillafix can be reproduced without, if i see vanillafix it does not matter what the bug is its an automatic request.

**Comment by gggg336** [comment]
No VanillaFix, same Buildcraft error as before with VanillaFix

With VanillaFix: https://paste.ee/p/Wh2kT
No VanillaFix: https://paste.ee/p/2LDh3

Edit: Removed Buildcraft and Minecraft loaded fine.

**Comment by Draskh** [comment]
I have installed the same mods and I had never this crash. 
Did you update your Forge version? Maybe this would help.

**Comment by CrankySupertoonArchive** [comment]
@NickelHub This is still a issue

**Comment by CrankySupertoonArchive** [comment]
[crash-2018-10-12_17.40.13-client.txt](https://github.com/MatterOverdrive/MatterOverdrive-Legacy-Edition/files/2474673/crash-2018-10-12_17.40.13-client.txt)

**Comment by CrankySupertoonArchive** [comment]
Looking at the log, it doesnt seem to like Buildcraft's Guide

**Comment by CrankySupertoonArchive** [comment]
And my forge is on .2766 I would do .2768 but it breaks ThaumCraft and some other mods

**Comment by CrankySupertoonArchive** [comment]
How is this spam, this is a valid bug report

**Comment by AlexIIL** [comment]
I assume because we know it's an issue but we (mod devs) haven't put sufficient time in to test it. (And there's not much point in uploading more crash reports when it's basically the same as the last one).

Instead what might be useful would be to find the smallest set of mods that causes this crash - your latest crash report has several hundred mods, but in theory this crash should only be caused by two or three of them. Can you retry with just BuildCraft and matteroverdrive? (I'm not really sure what else to suggest though, other than retrying with different combinations of mods. Or maybe it's config related?)

**Comment by Draskh** [comment]
I guess it's config related, since it happened to me. I had smiliar problem with Headcrumbs and Buildcraft. I will come back later to the Buildcraft issue and will look, if this is the same problem. But for now, there is nothing to do so.
